const allQuestions = [
  { q: "Do you like tea? – I …….", options: ["doesn't", "don't", "does"], correct: 1 },
  { q: "Which one is correct?", options: ["Give the book me!", "The book me give!", "Give me the book!"], correct: 2 },
  { q: "My girlfriend is …….", options: ["Italian", "Greece", "Sweden"], correct: 0 },
  { q: "Can I ……. you a question?", options: ["say", "ask", "listen"], correct: 1 },
  { q: "How ……. apples are there?", options: ["much", "many", "any"], correct: 1 },
  { q: "She ……. from London.", options: ["are", "is", "be"], correct: 1 },
  { q: "They ……. to school every day.", options: ["go", "goes", "going"], correct: 0 },
  { q: "We ……. dinner at 7 p.m.", options: ["have", "has", "having"], correct: 0 },
  { q: "Peter ……. play football.", options: ["don’t", "doesn’t", "isn’t"], correct: 1 },
  { q: "There ……. a book on the table.", options: ["is", "are", "be"], correct: 0 },
  { q: "I can’t ……. you.", options: ["listen", "hear", "say"], correct: 1 },
  { q: "She is ……. than her brother.", options: ["taller", "tallest", "more tall"], correct: 0 },
  { q: "What ……. your name?", options: ["is", "are", "be"], correct: 0 },
  { q: "I usually ……. TV in the evening.", options: ["watch", "watches", "watching"], correct: 0 },
  { q: "This is my ……. room.", options: ["sister", "sister’s", "sisters"], correct: 1 },
  { q: "There aren’t ……. chairs in the room.", options: ["some", "any", "a"], correct: 1 },
  { q: "I ……. bread for breakfast.", options: ["need", "needs", "needing"], correct: 0 },
  { q: "He ……. at the cinema now.", options: ["is", "are", "be"], correct: 0 },
  { q: "Where ……. you from?", options: ["is", "are", "be"], correct: 1 },
  { q: "She can ……. very well.", options: ["sings", "sing", "singing"], correct: 1 },

  { q: "He ……. at the cinema now.", options: ["is", "are", "be"], correct: 0 },
  { q: "They ……. very happy today.", options: ["is", "are", "be"], correct: 1 },
  { q: "I ……. from Hungary.", options: ["am", "is", "are"], correct: 0 },
  { q: "Where ……. you from?", options: ["is", "are", "am"], correct: 1 },
  { q: "My sister ……. in the kitchen.", options: ["is", "are", "be"], correct: 0 },
  { q: "Peter and John ……. friends.", options: ["is", "are", "am"], correct: 1 },
  { q: "She ……. a teacher.", options: ["am", "is", "are"], correct: 1 },
  { q: "They ……. students.", options: ["is", "are", "be"], correct: 1 },
  { q: "I ……. a doctor.", options: ["am", "is", "are"], correct: 0 },
  { q: "This ……. my book.", options: ["am", "is", "are"], correct: 1 },

  { q: "Do you like tea? – I …….", options: ["doesn't", "don't", "does"], correct: 1 },
  { q: "Peter ……. play football.", options: ["don’t", "doesn’t", "isn’t"], correct: 1 },
  { q: "She usually ……. TV in the evening.", options: ["watch", "watches", "watching"], correct: 1 },
  { q: "We often ……. to the cinema.", options: ["go", "goes", "going"], correct: 0 },
  { q: "My parents ……. in London.", options: ["live", "lives", "living"], correct: 0 },
  { q: "I ……. breakfast at 7 o’clock.", options: ["have", "has", "having"], correct: 0 },
  { q: "The sun ……. in the east.", options: ["rise", "rises", "rising"], correct: 1 },
  { q: "Water ……. at 100°C.", options: ["boil", "boils", "boiling"], correct: 1 },
  { q: "Tom always ……. to school by bus.", options: ["go", "goes", "going"], correct: 1 },
  { q: "She ……. English every day.", options: ["study", "studies", "studying"], correct: 1 },

  { q: "Look! The children ……. football.", options: ["play", "plays", "are playing"], correct: 2 },
  { q: "She ……. dinner now.", options: ["is cooking", "cooks", "cooking"], correct: 0 },
  { q: "Listen! The birds …….", options: ["sing", "sings", "are singing"], correct: 2 },
  { q: "He ……. in the garden at the moment.", options: ["works", "is working", "work"], correct: 1 },
  { q: "I ……. to music right now.", options: ["listen", "listening", "am listening"], correct: 2 },
  { q: "They ……. TV at the moment.", options: ["watch", "are watching", "watches"], correct: 1 },
  { q: "We ……. in the park now.", options: ["are walking", "walks", "walk"], correct: 0 },
  { q: "She ……. her homework at the moment.", options: ["does", "is doing", "do"], correct: 1 },
  { q: "The baby ……. now.", options: ["sleeping", "is sleeping", "sleeps"], correct: 1 },
  { q: "He ……. a letter right now.", options: ["write", "is writing", "writes"], correct: 1 },

  { q: "There ……. some apples on the table.", options: ["is", "are", "be"], correct: 1 },
  { q: "There ……. any bread in the fridge.", options: ["isn't", "aren't", "doesn't"], correct: 0 },
  { q: "Are there ……. chairs in the room?", options: ["some", "any", "much"], correct: 1 },
  { q: "There ……. a book on the desk.", options: ["is", "are", "be"], correct: 0 },
  { q: "How ……. water is in the bottle?", options: ["many", "much", "any"], correct: 1 },
  { q: "We don’t have ……. milk.", options: ["any", "some", "many"], correct: 0 },
  { q: "I need ……. sugar.", options: ["some", "any", "many"], correct: 0 },
  { q: "There aren’t ……. students here.", options: ["some", "any", "much"], correct: 1 },
  { q: "How ……. friends do you have?", options: ["much", "many", "any"], correct: 1 },
  { q: "She has ……. books in her bag.", options: ["many", "much", "any"], correct: 0 },

  { q: "My girlfriend is …….", options: ["Italian", "Greece", "Sweden"], correct: 0 },
  { q: "My friend is from …….", options: ["Italy", "Italian", "Italians"], correct: 0 },
  { q: "They are …….", options: ["Hungary", "Hungarian", "Hungarians"], correct: 1 },
  { q: "I am from …….", options: ["France", "French", "Frances"], correct: 0 },
  { q: "She is …….", options: ["Spain", "Spanish", "Spains"], correct: 1 },
  { q: "We live in …….", options: ["Germany", "German", "Germans"], correct: 0 },
  { q: "He is a ……. student.", options: ["Germany", "German", "Germans"], correct: 1 },
  { q: "Are you …….?", options: ["England", "English", "Englands"], correct: 1 },
  { q: "She comes from …….", options: ["Poland", "Polish", "Polishes"], correct: 0 },
  { q: "He is …….", options: ["Poland", "Polish", "Polishes"], correct: 1 },


];

