const allQuestions = [
  { q: "Do you like tea? – I …….", options: ["doesn't", "don't", "does"], correct: 1 },
  { q: "Which one is correct?", options: ["Give the book me!", "The book me give!", "Give me the book!"], correct: 2 },
  { q: "My girlfriend is …….", options: ["Italian", "Greece", "Sweden"], correct: 0 },
  { q: "Can I ……. you a question?", options: ["say", "ask", "listen"], correct: 1 },
  { q: "How ……. apples are there?", options: ["much", "many", "any"], correct: 1 },
  { q: "She ……. from London.", options: ["are", "is", "be"], correct: 1 },
  { q: "They ……. to school every day.", options: ["go", "goes", "going"], correct: 0 },
  { q: "We ……. dinner at 7 p.m.", options: ["have", "has", "having"], correct: 0 },
  { q: "Peter ……. play football.", options: ["don’t", "doesn’t", "isn’t"], correct: 1 },
  { q: "There ……. a book on the table.", options: ["is", "are", "be"], correct: 0 },
  { q: "I can’t ……. you.", options: ["listen", "hear", "say"], correct: 1 },
  { q: "She is ……. than her brother.", options: ["taller", "tallest", "more tall"], correct: 0 },
  { q: "What ……. your name?", options: ["is", "are", "be"], correct: 0 },
  { q: "I usually ……. TV in the evening.", options: ["watch", "watches", "watching"], correct: 0 },
  { q: "This is my ……. room.", options: ["sister", "sister’s", "sisters"], correct: 1 },
  { q: "There aren’t ……. chairs in the room.", options: ["some", "any", "a"], correct: 1 },
  { q: "I ……. bread for breakfast.", options: ["need", "needs", "needing"], correct: 0 },
  { q: "He ……. at the cinema now.", options: ["is", "are", "be"], correct: 0 },
  { q: "Where ……. you from?", options: ["is", "are", "be"], correct: 1 },
  { q: "She can ……. very well.", options: ["sings", "sing", "singing"], correct: 1 },

  { q: "He ……. at the cinema now.", options: ["is", "are", "be"], correct: 0 },
  { q: "They ……. very happy today.", options: ["is", "are", "be"], correct: 1 },
  { q: "I ……. from Hungary.", options: ["am", "is", "are"], correct: 0 },
  { q: "Where ……. you from?", options: ["is", "are", "am"], correct: 1 },
  { q: "My sister ……. in the kitchen.", options: ["is", "are", "be"], correct: 0 },
  { q: "Peter and John ……. friends.", options: ["is", "are", "am"], correct: 1 },
  { q: "She ……. a teacher.", options: ["am", "is", "are"], correct: 1 },
  { q: "They ……. students.", options: ["is", "are", "be"], correct: 1 },
  { q: "I ……. a doctor.", options: ["am", "is", "are"], correct: 0 },
  { q: "This ……. my book.", options: ["am", "is", "are"], correct: 1 },

  { q: "Do you like tea? – I …….", options: ["doesn't", "don't", "does"], correct: 1 },
  { q: "Peter ……. play football.", options: ["don’t", "doesn’t", "isn’t"], correct: 1 },
  { q: "She usually ……. TV in the evening.", options: ["watch", "watches", "watching"], correct: 1 },
  { q: "We often ……. to the cinema.", options: ["go", "goes", "going"], correct: 0 },
  { q: "My parents ……. in London.", options: ["live", "lives", "living"], correct: 0 },
  { q: "I ……. breakfast at 7 o’clock.", options: ["have", "has", "having"], correct: 0 },
  { q: "The sun ……. in the east.", options: ["rise", "rises", "rising"], correct: 1 },
  { q: "Water ……. at 100°C.", options: ["boil", "boils", "boiling"], correct: 1 },
  { q: "Tom always ……. to school by bus.", options: ["go", "goes", "going"], correct: 1 },
  { q: "She ……. English every day.", options: ["study", "studies", "studying"], correct: 1 },

  { q: "Look! The children ……. football.", options: ["play", "plays", "are playing"], correct: 2 },
  { q: "She ……. dinner now.", options: ["is cooking", "cooks", "cooking"], correct: 0 },
  { q: "Listen! The birds …….", options: ["sing", "sings", "are singing"], correct: 2 },
  { q: "He ……. in the garden at the moment.", options: ["works", "is working", "work"], correct: 1 },
  { q: "I ……. to music right now.", options: ["listen", "listening", "am listening"], correct: 2 },
  { q: "They ……. TV at the moment.", options: ["watch", "are watching", "watches"], correct: 1 },
  { q: "We ……. in the park now.", options: ["are walking", "walks", "walk"], correct: 0 },
  { q: "She ……. her homework at the moment.", options: ["does", "is doing", "do"], correct: 1 },
  { q: "The baby ……. now.", options: ["sleeping", "is sleeping", "sleeps"], correct: 1 },
  { q: "He ……. a letter right now.", options: ["write", "is writing", "writes"], correct: 1 },

  { q: "There ……. some apples on the table.", options: ["is", "are", "be"], correct: 1 },
  { q: "There ……. any bread in the fridge.", options: ["isn't", "aren't", "doesn't"], correct: 0 },
  { q: "Are there ……. chairs in the room?", options: ["some", "any", "much"], correct: 1 },
  { q: "There ……. a book on the desk.", options: ["is", "are", "be"], correct: 0 },
  { q: "How ……. water is in the bottle?", options: ["many", "much", "any"], correct: 1 },
  { q: "We don’t have ……. milk.", options: ["any", "some", "many"], correct: 0 },
  { q: "I need ……. sugar.", options: ["some", "any", "many"], correct: 0 },
  { q: "There aren’t ……. students here.", options: ["some", "any", "much"], correct: 1 },
  { q: "How ……. friends do you have?", options: ["much", "many", "any"], correct: 1 },
  { q: "She has ……. books in her bag.", options: ["many", "much", "any"], correct: 0 },

  { q: "My girlfriend is …….", options: ["Italian", "Greece", "Sweden"], correct: 0 },
  { q: "My friend is from …….", options: ["Italy", "Italian", "Italians"], correct: 0 },
  { q: "They are …….", options: ["Hungary", "Hungarian", "Hungarians"], correct: 1 },
  { q: "I am from …….", options: ["France", "French", "Frances"], correct: 0 },
  { q: "She is …….", options: ["Spain", "Spanish", "Spains"], correct: 1 },
  { q: "We live in …….", options: ["Germany", "German", "Germans"], correct: 0 },
  { q: "He is a ……. student.", options: ["Germany", "German", "Germans"], correct: 1 },
  { q: "Are you …….?", options: ["England", "English", "Englands"], correct: 1 },
  { q: "She comes from …….", options: ["Poland", "Polish", "Polishes"], correct: 0 },
  { q: "He is …….", options: ["Poland", "Polish", "Polishes"], correct: 1 },
  const allQuestions = [
  { q: "Do you like tea? – I …….", options: ["doesn't", "don't", "does"], correct: 1 },
  { q: "Which one is correct?", options: ["Give the book me!", "The book me give!", "Give me the book!"], correct: 2 },
  { q: "My girlfriend is …….", options: ["Italian", "Greece", "Sweden"], correct: 0 },
  { q: "Can I ……. you a question?", options: ["say", "ask", "listen"], correct: 1 },
  { q: "How ……. apples are there?", options: ["much", "many", "any"], correct: 1 },
  { q: "She ……. from London.", options: ["are", "is", "be"], correct: 1 },
  { q: "They ……. to school every day.", options: ["go", "goes", "going"], correct: 0 },
  { q: "We ……. dinner at 7 p.m.", options: ["have", "has", "having"], correct: 0 },
  { q: "Peter ……. play football.", options: ["don’t", "doesn’t", "isn’t"], correct: 1 },
  { q: "There ……. a book on the table.", options: ["is", "are", "be"], correct: 0 },
  { q: "I can’t ……. you.", options: ["listen", "hear", "say"], correct: 1 },
  { q: "She is ……. than her brother.", options: ["taller", "tallest", "more tall"], correct: 0 },
  { q: "What ……. your name?", options: ["is", "are", "be"], correct: 0 },
  { q: "I usually ……. TV in the evening.", options: ["watch", "watches", "watching"], correct: 0 },
  { q: "This is my ……. room.", options: ["sister", "sister’s", "sisters"], correct: 1 },
  { q: "There aren’t ……. chairs in the room.", options: ["some", "any", "a"], correct: 1 },
  { q: "I ……. bread for breakfast.", options: ["need", "needs", "needing"], correct: 0 },
  { q: "He ……. at the cinema now.", options: ["is", "are", "be"], correct: 0 },
  { q: "Where ……. you from?", options: ["is", "are", "be"], correct: 1 },
  { q: "She can ……. very well.", options: ["sings", "sing", "singing"], correct: 1 },

  { q: "He ……. at the cinema now.", options: ["is", "are", "be"], correct: 0 },
  { q: "They ……. very happy today.", options: ["is", "are", "be"], correct: 1 },
  { q: "I ……. from Hungary.", options: ["am", "is", "are"], correct: 0 },
  { q: "Where ……. you from?", options: ["is", "are", "am"], correct: 1 },
  { q: "My sister ……. in the kitchen.", options: ["is", "are", "be"], correct: 0 },
  { q: "Peter and John ……. friends.", options: ["is", "are", "am"], correct: 1 },
  { q: "She ……. a teacher.", options: ["am", "is", "are"], correct: 1 },
  { q: "They ……. students.", options: ["is", "are", "be"], correct: 1 },
  { q: "I ……. a doctor.", options: ["am", "is", "are"], correct: 0 },
  { q: "This ……. my book.", options: ["am", "is", "are"], correct: 1 },

  { q: "Do you like tea? – I …….", options: ["doesn't", "don't", "does"], correct: 1 },
  { q: "Peter ……. play football.", options: ["don’t", "doesn’t", "isn’t"], correct: 1 },
  { q: "She usually ……. TV in the evening.", options: ["watch", "watches", "watching"], correct: 1 },
  { q: "We often ……. to the cinema.", options: ["go", "goes", "going"], correct: 0 },
  { q: "My parents ……. in London.", options: ["live", "lives", "living"], correct: 0 },
  { q: "I ……. breakfast at 7 o’clock.", options: ["have", "has", "having"], correct: 0 },
  { q: "The sun ……. in the east.", options: ["rise", "rises", "rising"], correct: 1 },
  { q: "Water ……. at 100°C.", options: ["boil", "boils", "boiling"], correct: 1 },
  { q: "Tom always ……. to school by bus.", options: ["go", "goes", "going"], correct: 1 },
  { q: "She ……. English every day.", options: ["study", "studies", "studying"], correct: 1 },

  { q: "Look! The children ……. football.", options: ["play", "plays", "are playing"], correct: 2 },
  { q: "She ……. dinner now.", options: ["is cooking", "cooks", "cooking"], correct: 0 },
  { q: "Listen! The birds …….", options: ["sing", "sings", "are singing"], correct: 2 },
  { q: "He ……. in the garden at the moment.", options: ["works", "is working", "work"], correct: 1 },
  { q: "I ……. to music right now.", options: ["listen", "listening", "am listening"], correct: 2 },
  { q: "They ……. TV at the moment.", options: ["watch", "are watching", "watches"], correct: 1 },
  { q: "We ……. in the park now.", options: ["are walking", "walks", "walk"], correct: 0 },
  { q: "She ……. her homework at the moment.", options: ["does", "is doing", "do"], correct: 1 },
  { q: "The baby ……. now.", options: ["sleeping", "is sleeping", "sleeps"], correct: 1 },
  { q: "He ……. a letter right now.", options: ["write", "is writing", "writes"], correct: 1 },

  { q: "There ……. some apples on the table.", options: ["is", "are", "be"], correct: 1 },
  { q: "There ……. any bread in the fridge.", options: ["isn't", "aren't", "doesn't"], correct: 0 },
  { q: "Are there ……. chairs in the room?", options: ["some", "any", "much"], correct: 1 },
  { q: "There ……. a book on the desk.", options: ["is", "are", "be"], correct: 0 },
  { q: "How ……. water is in the bottle?", options: ["many", "much", "any"], correct: 1 },
  { q: "We don’t have ……. milk.", options: ["any", "some", "many"], correct: 0 },
  { q: "I need ……. sugar.", options: ["some", "any", "many"], correct: 0 },
  { q: "There aren’t ……. students here.", options: ["some", "any", "much"], correct: 1 },
  { q: "How ……. friends do you have?", options: ["much", "many", "any"], correct: 1 },
  { q: "She has ……. books in her bag.", options: ["many", "much", "any"], correct: 0 },

  { q: "My girlfriend is …….", options: ["Italian", "Greece", "Sweden"], correct: 0 },
  { q: "My friend is from …….", options: ["Italy", "Italian", "Italians"], correct: 0 },
  { q: "They are …….", options: ["Hungary", "Hungarian", "Hungarians"], correct: 1 },
  { q: "I am from …….", options: ["France", "French", "Frances"], correct: 0 },
  { q: "She is …….", options: ["Spain", "Spanish", "Spains"], correct: 1 },
  { q: "We live in …….", options: ["Germany", "German", "Germans"], correct: 0 },
  { q: "He is a ……. student.", options: ["Germany", "German", "Germans"], correct: 1 },
  { q: "Are you …….?", options: ["England", "English", "Englands"], correct: 1 },
  { q: "She comes from …….", options: ["Poland", "Polish", "Polishes"], correct: 0 },
  { q: "He is …….", options: ["Poland", "Polish", "Polishes"], correct: 1 },

  { q: "Do you like tea? – I …….", options: ["doesn't", "don't", "does"], correct: 1 },
  { q: "She ……. from London.", options: ["am", "is", "are"], correct: 1 },
  { q: "They ……. playing football now.", options: ["is", "are", "be"], correct: 1 },
  { q: "My brother ……. like pizza.", options: ["don't", "doesn't", "isn't"], correct: 1 },
  { q: "We ……. to school yesterday.", options: ["go", "went", "gone"], correct: 1 },
  { q: "He ……. a car.", options: ["have", "has", "haves"], correct: 1 },
  { q: "Where ……. you live?", options: ["do", "does", "is"], correct: 0 },
  { q: "She ……. TV every evening.", options: ["watch", "watches", "watching"], correct: 1 },
  { q: "I ……. reading a book now.", options: ["am", "is", "are"], correct: 0 },
  { q: "They ……. at home last night.", options: ["was", "were", "are"], correct: 1 },
  { q: "He ……. go to school on Sundays.", options: ["doesn't", "don't", "isn't"], correct: 0 },
  { q: "We ……. breakfast at 7 o’clock.", options: ["have", "has", "having"], correct: 0 },
  { q: "The children ……. in the park now.", options: ["is", "are", "be"], correct: 1 },
  { q: "She ……. English very well.", options: ["speak", "speaks", "speaking"], correct: 1 },
  { q: "I ……. my homework yesterday.", options: ["do", "did", "done"], correct: 1 },
  { q: "They ……. to the cinema every week.", options: ["go", "goes", "going"], correct: 0 },
  { q: "He ……. not at school today.", options: ["is", "are", "am"], correct: 0 },
  { q: "What time ……. you get up?", options: ["do", "does", "is"], correct: 0 },
  { q: "We ……. in Budapest now.", options: ["are", "is", "be"], correct: 0 },
  { q: "My father ……. coffee in the morning.", options: ["drink", "drinks", "drinking"], correct: 1 },
  { q: "She ……. not like fish.", options: ["does", "doesn't", "don't"], correct: 1 },
  { q: "I ……. swimming every Saturday.", options: ["go", "goes", "going"], correct: 0 },
  { q: "They ……. a big house.", options: ["have", "has", "haves"], correct: 0 },
  { q: "We ……. happy yesterday.", options: ["was", "were", "are"], correct: 1 },
  { q: "My sister ……. fifteen years old.", options: ["is", "are", "am"], correct: 0 },
  { q: "She ……. to music now.", options: ["listen", "listens", "is listening"], correct: 2 },
  { q: "They ……. a dog.", options: ["have", "has", "haves"], correct: 0 },
  { q: "I ……. to the shop yesterday.", options: ["go", "went", "gone"], correct: 1 },
  { q: "He ……. tennis on Mondays.", options: ["play", "plays", "playing"], correct: 1 },
  { q: "We ……. friends.", options: ["am", "is", "are"], correct: 2 },
  { q: "You ……. late yesterday.", options: ["was", "were", "are"], correct: 1 },
  { q: "She ……. going to school now.", options: ["is", "are", "am"], correct: 0 },
  { q: "They ……. not hungry.", options: ["are", "is", "be"], correct: 0 },
  { q: "I ……. like coffee.", options: ["don't", "doesn't", "isn't"], correct: 0 },
  { q: "Where ……. he work?", options: ["do", "does", "is"], correct: 1 },
  { q: "We ……. football yesterday.", options: ["play", "played", "playing"], correct: 1 },
  { q: "She ……. not here yesterday.", options: ["was", "were", "is"], correct: 0 },
  { q: "My parents ……. in London now.", options: ["is", "are", "be"], correct: 1 },
  { q: "He ……. playing the piano.", options: ["is", "are", "be"], correct: 0 },
  { q: "They ……. English every day.", options: ["study", "studies", "studying"], correct: 0 },
  { q: "I ……. a teacher.", options: ["am", "is", "are"], correct: 0 },
  { q: "She ……. a doctor.", options: ["am", "is", "are"], correct: 1 },
  { q: "We ……. to the park tomorrow.", options: ["go", "goes", "will go"], correct: 2 },
  { q: "They ……. not tired now.", options: ["are", "is", "be"], correct: 0 },
  { q: "He ……. at home now.", options: ["is", "are", "be"], correct: 0 },
  { q: "I ……. a book yesterday.", options: ["read", "reads", "reading"], correct: 0 },
  { q: "We ……. not go to the party.", options: ["did", "didn't", "don't"], correct: 1 },
  { q: "She ……. her homework now.", options: ["do", "does", "is doing"], correct: 2 },
  { q: "They ……. here last night.", options: ["was", "were", "are"], correct: 1 },
  { q: "He ……. playing football yesterday.", options: ["was", "were", "is"], correct: 0 },
  { q: "We ……. hungry now.", options: ["am", "is", "are"], correct: 2 },
  { q: "I ……. not at school yesterday.", options: ["was", "were", "am"], correct: 0 },
  { q: "They ……. to the zoo tomorrow.", options: ["go", "will go", "goes"], correct: 1 },
  { q: "She ……. not working now.", options: ["is", "are", "was"], correct: 0 },
  { q: "I ……. TV yesterday evening.", options: ["watch", "watched", "watching"], correct: 1 },
  { q: "We ……. English now.", options: ["learn", "are learning", "learning"], correct: 1 },
  { q: "They ……. not play yesterday.", options: ["did", "didn't", "don't"], correct: 1 },
  { q: "He ……. a student.", options: ["am", "is", "are"], correct: 1 },
  { q: "I ……. a letter yesterday.", options: ["write", "wrote", "written"], correct: 1 },
  { q: "They ……. going to the park now.", options: ["is", "are", "be"], correct: 1 },
  { q: "She ……. tennis yesterday.", options: ["play", "played", "playing"], correct: 1 },
  { q: "We ……. not at home yesterday.", options: ["was", "were", "are"], correct: 1 },
  { q: "I ……. not like milk.", options: ["don't", "doesn't", "isn't"], correct: 0 },
  { q: "They ……. football now.", options: ["is", "are", "be"], correct: 1 },
  { q: "She ……. to school every day.", options: ["go", "goes", "going"], correct: 1 },
  { q: "We ……. happy now.", options: ["am", "is", "are"], correct: 2 },
  { q: "He ……. not here tomorrow.", options: ["will", "won’t be", "isn't"], correct: 1 },
  { q: "I ……. English every day.", options: ["study", "studies", "studying"], correct: 0 },
  { q: "They ……. not swim yesterday.", options: ["did", "didn't", "don't"], correct: 1 },
  { q: "She ……. a book now.", options: ["is reading", "read", "reads"], correct: 0 },
  { q: "We ……. at home yesterday.", options: ["was", "were", "are"], correct: 1 },
  { q: "He ……. not a doctor.", options: ["is", "isn't", "aren't"], correct: 1 },
  { q: "They ……. English now.", options: ["learn", "are learning", "learning"], correct: 1 },
  { q: "I ……. to the park every day.", options: ["go", "goes", "going"], correct: 0 },
  { q: "She ……. not go to school yesterday.", options: ["did", "didn't", "doesn't"], correct: 1 },
  { q: "We ……. in London now.", options: ["are", "is", "be"], correct: 0 },
  { q: "They ……. football yesterday.", options: ["play", "played", "playing"], correct: 1 },
  { q: "I ……. not here now.", options: ["am", "is", "are"], correct: 0 },
  { q: "He ……. to the shop every day.", options: ["go", "goes", "going"], correct: 1 },
  { q: "She ……. not in London now.", options: ["is", "isn't", "aren't"], correct: 1 },
  { q: "We ……. to the cinema tomorrow.", options: ["go", "will go", "goes"], correct: 1 },
  { q: "They ……. here now.", options: ["am", "is", "are"], correct: 2 },
  { q: "I ……. not like tea.", options: ["don't", "doesn't", "isn't"], correct: 0 },
  { q: "She ……. English now.", options: ["learn", "learns", "is learning"], correct: 2 },
  { q: "We ……. not go yesterday.", options: ["did", "didn't", "don't"], correct: 1 },
  { q: "They ……. playing now.", options: ["is", "are", "be"], correct: 1 },
  { q: "He ……. football every day.", options: ["play", "plays", "playing"], correct: 1 },
  { q: "I ……. to school yesterday.", options: ["go", "went", "gone"], correct: 1 },
  { q: "We ……. not happy yesterday.", options: ["was", "were", "are"], correct: 1 },
  { q: "She ……. a teacher.", options: ["am", "is", "are"], correct: 1 },
  { q: "They ……. to the zoo yesterday.", options: ["go", "went", "gone"], correct: 1 },
  { q: "He ……. not in the park now.", options: ["is", "isn't", "aren't"], correct: 1 },
  { q: "I ……. a car.", options: ["have", "has", "haves"], correct: 0 },
  { q: "We ……. not go tomorrow.", options: ["will", "won't", "don't"], correct: 1 },
  { q: "She ……. a student.", options: ["am", "is", "are"], correct: 1 },
  { q: "They ……. not at home yesterday.", options: ["was", "were", "are"], correct: 1 },
  { q: "I ……. English now.", options: ["am learning", "learn", "learns"], correct: 0 },
  { q: "He ……. not like fish.", options: ["doesn't", "don't", "isn't"], correct: 0 },
  { q: "We ……. a dog.", options: ["have", "has", "haves"], correct: 0 },


];






